kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji

title: Assembleur x86_64 (En travaux)
description:
  Quelques notes Ã  propos de l'architecture x86_64 sous l'ABI amd64 linux.
  Notez que les instructions des exemples suivent la syntaxe AT&T.
# show_downloads: [true]
